//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMdfEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_config_puertos
    {
        public long pkConfigPuerto { get; set; }
        public string nombre_dispositivo { get; set; }
        public Nullable<int> status { get; set; }
        public string port_name { get; set; }
        public string baud_rate { get; set; }
        public string data_bits { get; set; }
        public string stop_bits { get; set; }
        public string paridad { get; set; }
        public string handshake { get; set; }
        public Nullable<int> enviado { get; set; }
        public Nullable<int> confirmado { get; set; }
        public Nullable<int> modo { get; set; }
        public string deleted_at { get; set; }
        public string updated_at { get; set; }
        public string created_at { get; set; }
    }
}
