//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMdfEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_denominaciones
    {
        public long pkDenominacion { get; set; }
        public string nombre { get; set; }
        public string valor { get; set; }
        public string path_imagen { get; set; }
        public byte[] bin_imagen { get; set; }
        public Nullable<int> posicion { get; set; }
        public Nullable<int> status { get; set; }
        public string deleted_at { get; set; }
        public string updated_at { get; set; }
        public string created_at { get; set; }
    }
}
