//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMdfEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_usuarios
    {
        public long pkUsuario { get; set; }
        public long fkPuesto { get; set; }
        public long fkStatus { get; set; }
        public string nombre { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public string token { get; set; }
        public string tipo_usuario { get; set; }
        public Nullable<int> enviado { get; set; }
        public Nullable<int> confirmado { get; set; }
        public Nullable<int> modo { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public string deleted_at { get; set; }
        public Nullable<long> created_id { get; set; }
        public Nullable<long> updated_id { get; set; }
        public Nullable<long> deleted_id { get; set; }
    }
}
