//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMdfEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_unidades
    {
        public long pkUnidad { get; set; }
        public Nullable<long> fkEmpresa { get; set; }
        public Nullable<long> fkCorredor { get; set; }
        public string nombre { get; set; }
        public string noSerieAVL { get; set; }
        public string economico { get; set; }
        public Nullable<int> capacidad { get; set; }
        public Nullable<int> validador { get; set; }
        public Nullable<int> status { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public string deleted_at { get; set; }
    }
}
