//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMdfEntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class databaseEntities : DbContext
    {
        public databaseEntities()
            : base("name=databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<config_varios> config_varios { get; set; }
        public virtual DbSet<opciones_generales> opciones_generales { get; set; }
        public virtual DbSet<ct_andadores> ct_andadores { get; set; }
        public virtual DbSet<sy_tarifas> sy_tarifas { get; set; }
        public virtual DbSet<ct_alcancias> ct_alcancias { get; set; }
        public virtual DbSet<ct_consolas> ct_consolas { get; set; }
        public virtual DbSet<ct_taquillas> ct_taquillas { get; set; }
        public virtual DbSet<ct_corredores> ct_corredores { get; set; }
        public virtual DbSet<ct_empresas> ct_empresas { get; set; }
        public virtual DbSet<ct_lugares> ct_lugares { get; set; }
        public virtual DbSet<ct_operadores> ct_operadores { get; set; }
        public virtual DbSet<ct_perfiles> ct_perfiles { get; set; }
        public virtual DbSet<ct_rutas> ct_rutas { get; set; }
        public virtual DbSet<sy_status> sy_status { get; set; }
        public virtual DbSet<sy_asignaciones> sy_asignaciones { get; set; }
        public virtual DbSet<ct_unidades> ct_unidades { get; set; }
        public virtual DbSet<sy_boletos_detalle> sy_boletos_detalle { get; set; }
        public virtual DbSet<sy_boletos> sy_boletos { get; set; }
        public virtual DbSet<sy_mensajes> sy_mensajes { get; set; }
        public virtual DbSet<sy_ubicacion> sy_ubicacion { get; set; }
        public virtual DbSet<ct_denominaciones> ct_denominaciones { get; set; }
        public virtual DbSet<ct_imagenes_subidas> ct_imagenes_subidas { get; set; }
        public virtual DbSet<ct_tarifas_montos_fijos> ct_tarifas_montos_fijos { get; set; }
        public virtual DbSet<sy_boletos_tarifa_fija> sy_boletos_tarifa_fija { get; set; }
        public virtual DbSet<sy_cortes> sy_cortes { get; set; }
        public virtual DbSet<sy_lugar_ruta> sy_lugar_ruta { get; set; }
        public virtual DbSet<sy_empresa_corredor_operador> sy_empresa_corredor_operador { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<ct_usuarios> ct_usuarios { get; set; }
    }
}
