//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMdfEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_asignaciones
    {
        public long pkAsignacion { get; set; }
        public Nullable<long> fkRuta { get; set; }
        public Nullable<long> fkUnidad { get; set; }
        public Nullable<long> fkOperador { get; set; }
        public Nullable<long> fkAndador { get; set; }
        public Nullable<long> fkLiquidacion { get; set; }
        public Nullable<long> fkStatus { get; set; }
        public string folio { get; set; }
        public string fecha { get; set; }
        public string hora { get; set; }
        public Nullable<int> ihora { get; set; }
        public Nullable<int> cantidadAsientosDisp { get; set; }
        public Nullable<int> recurrente { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public string deleted_at { get; set; }
    }
}
