//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMdfEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_boletos_detalle
    {
        public long pkBoletoDetalle { get; set; }
        public Nullable<long> pkBoletoDetalleTISA { get; set; }
        public Nullable<long> fkBoleto { get; set; }
        public Nullable<long> fkPerfil { get; set; }
        public Nullable<long> fkTarifa { get; set; }
        public Nullable<long> fkStatus { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<int> enviado { get; set; }
        public Nullable<int> confirmadoTISA { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public string deleted_at { get; set; }
    }
}
