//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMdfEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_conteo_cuenta_cocos
    {
        public long pkConteoCuentaCocos { get; set; }
        public Nullable<long> pkConteoCuentaCocosTISA { get; set; }
        public Nullable<long> fkAsignacion { get; set; }
        public Nullable<long> fkStatus { get; set; }
        public Nullable<long> cc1_subidas { get; set; }
        public Nullable<long> cc1_bajadas { get; set; }
        public Nullable<long> cc2_subidas { get; set; }
        public Nullable<long> cc2_bajadas { get; set; }
        public Nullable<long> cc3_subidas { get; set; }
        public Nullable<long> cc3_bajadas { get; set; }
        public string fecha_hora { get; set; }
        public Nullable<int> enviado { get; set; }
        public Nullable<int> confirmado { get; set; }
        public Nullable<int> modo { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public string deleted_at { get; set; }
    }
}
