//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMdfEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_mensajes
    {
        public long pkMensaje { get; set; }
        public Nullable<long> fkAsignacion { get; set; }
        public Nullable<long> fkStatus { get; set; }
        public string mensaje { get; set; }
        public Nullable<int> enviado { get; set; }
        public Nullable<int> confirmadoTISA { get; set; }
        public string modo { get; set; }
        public Nullable<int> dispositivo_origen { get; set; }
        public Nullable<int> dispositivo_destino { get; set; }
        public Nullable<int> reproducido { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public string deleted_at { get; set; }
    }
}
