//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMdfEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_tarifas
    {
        public long pkTarifa { get; set; }
        public long fkLugarOrigen { get; set; }
        public long fkLugarDestino { get; set; }
        public long fkPerfil { get; set; }
        public decimal monto { get; set; }
        public Nullable<int> status { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public string deleted_at { get; set; }
    }
}
